config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles #, only: [:show, :index,:new, :create, :update, :edit, :destroy]
  get 'signup', to: 'users#new'
  resources :users , except: [:new]
  get 'login' , to:'sessions#new'
  post 'login' , to:'sessions#create'
  delete 'logout' , to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title , presence: true , length: {minimum: 6, maximum: 100}
  validates :description , presence: true, length: {minimum: 10 , maximum: 300}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord

  before_save { self.email = email.downcase}
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
            length: { minimum: 3, maximum:25 },
            uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
            length: { maximum:105 },
            uniqueness: { case_sensitive: false },
            format: {with: VALID_EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show,:edit,:update,:destroy]
  before_action :require_user, except: [:show,:index]
  before_action :require_same_user, only: [:edit,:update,:destroy]

  def show

    [
      {
        name:'Tennis nike',
        description:'tennis de ultima de generacion',
        variants:[
          {
            name:'talla 32',
            price:12222,

          },
          {
            name:'talla 32',
            price:12222,
          }
        ]
      }
    ]

  end

  def index
    @article = Article.all
  end

  def new
    @article=Article.new

  end

  def edit
  end

  def create
    #render plain: params[:article]
    @article = Article.new(article_params)
    @article.user = current_user
    #render plain: @article.inspect
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to article_path(@article)
    else
      render 'new'
    end


  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was update successfully"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy

    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title,:description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end



end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  before_action :set_category, only: [:show, :edit, :update]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = " Category was successfully created"
      redirect_to @category
    else
      render 'new'
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @article = @category.articles
  end

  def edit
  end

  def update
    if  @category.update(category_params)
      flash[:notice] = "category name updated successfully"
      redirect_to @category
    else
      render 'edit'
    end

  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform thar action"
      redirect_to categories_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert]  = "There was something wrong with your login details"
      render 'new'
    end

  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "logged out"
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show,:edit,:update,:destroy]
  before_action :require_user, only: [:edit,:update]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  def show
    @article = @user.articles
  end

  def index
    @users= User.paginate(page: params[:page], per_page: 5)

  end

  def new
    @user=User.new
  end

  def edit
  end

  def update
    if  @user.update(user_params)
      flash[:notice] = "Your account information was successfully update"
      redirect_to articles_path
    else
      render 'edit'
    end


  end

  def create
    @user= User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the alpha Blog #{@user.username},you have successfully signup"
      redirect_to articles_path
    else
      render 'new'
    end

  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to articles_path
  end



  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user,option={size: 80})
    email_address= user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = option[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt:  user.username, class:'mt-5 rounded-xl shadow-xl')
  end





end

app/views/articles/_articles.html.erb
<table class="min-w-full leading-normal">
  <thead>
  <tr>
    <th
      class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-center text-xs font-semibold text-gray-600 uppercase tracking-wider">
      Title
    </th>
    <th
      class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-center text-xs font-semibold text-gray-600 uppercase tracking-wider">
      Description
    </th>
    <th
      class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-center text-xs font-semibold text-gray-600 uppercase tracking-wider">
      User
    </th>
    <th colspan="3"
        class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-center text-xs font-semibold text-gray-600 uppercase tracking-wider">
      Action
    </th>

      <th
        class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-center text-xs font-semibold text-gray-600 uppercase tracking-wider">
        Categories
      </th>

  </tr>
  </thead>
  <tbody>
  <% @article.each do |article| %>
    <tr>
      <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
        <p class="text-gray-900 whitespace-no-wrap text-center"><%= article.title %></p>
      </td>
      <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
        <p class="text-gray-900 whitespace-no-wrap text-center"><%= article.description %></p>
      </td>
      <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
        <p class="text-gray-900 whitespace-no-wrap text-center"><%= article.user.username if article.user%></p>
      </td>
      <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
        <p class="underline  text-blue-500 whitespace-no-wrap text-center"><%= link_to 'Show', article_path(article)  %></p>
      </td>
      <% if logged_in? && (article.user == current_user || current_user.admin?) %>
        <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
          <p class="underline  text-blue-500 whitespace-no-wrap text-center"><%= link_to 'Delete', article_path(article), method: :delete , data: { confirm: "are you sure?"}  %></p>

        </td>
        <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
          <p class="underline text-blue-500 whitespace-no-wrap text-center"><%= link_to 'Edit', edit_article_path(article)  %></p>

        </td>
      <% end %>
      <% if article.categories.any? %>
        <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
          <%= render article.categories %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
<h2 class="underline text-blue-500 whitespace-no-wrap text-center">
  <%= link_to 'Crate new article' , new_article_path %>
</h2>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h1>Thr followinf erros prevented the article from being seved</h1>
  <ul class="ml-5 list-disc bg-gray-200 ">
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>

  </ul>


<% end %>
<%= form_with(model: @article , local: true) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title , class:"shadow appearance-none border border-red-500 rounded  py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" %>
  </p>
  <p>
    <%= f.label :description , class:"font-bold" %><br>
    <%= f.text_area :description ,class:"shadow appearance-none border border-red-500 rounded  py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"%>
  </p>
  <label class="block text-left" style="max-width: 300px;">
    <span class="text-gray-700">Category</span>
    <%= f.collection_select(:category_ids, Category.all, :id, :name,
        { prompt: "Make your selection from the list below(can be empty" }, { multiple: true, class:'form-multiselect block w-full mt-1' })
    %>  </label>

  <p>
    <%= f.submit  %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1 class="font-bold text-2xl text-center mt-10">Edit article</h1>
<%= render 'form' %>

<p class="underline text-blue-500 ">
  <%= link_to 'Return to articles listing' , articles_path%>
</p>

app/views/articles/index.html.erb
<h1 class="text-black text-2xl font-bold text-center">Articles list page</h1>

<%= render 'articles'%>

app/views/articles/new.html.erb
<h1 class="font-bold text-2xl text-center mt-10">Create new article</h1>
<%= render 'form' %>
<p class="underline text-blue-500 ">
  <%= link_to 'Return to articles listing' , articles_path%>
</p>

app/views/articles/show.html.erb
<h1 class="text-xl text-blue-500 text-start">Showing article details</h1>
<p><span class="font-bold">by: </span><%= @article.user.username if @article.user %></p>
<p><span class="font-bold">title: </span><%= @article.title %></p>
<p><span class="font-bold">description: </span><%= @article.description %></p>
<% if @article.categories.any? %>
  <%= render @article.categories %>
<% end %>

<% if logged_in? && (@article.user == current_user && current_user.admin?) %>
  <p class="underline text-blue-500 w">
    <%= link_to 'Edit article' , edit_article_path(@article) %>
  </p>
  <p class="underline text-blue-500  r">
    <%= link_to 'Delete article' , article_path(@article) , method: :delete, data: { confirm: "are you sure?"}%>
  </p>
<% end %>
<p class="underline text-blue-500 ">
  <%= link_to 'Return to articles listing' , articles_path%>
</p>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: 'inline-flex items-center mr-2 justify-center px-2 py-1 text-xs font-bold leading-none text-red-100 bg-red-600 rounded-full' %>

app/views/categories/_form.html.erb
<div class="flex justify-center mt-10">

  <div class="w-full max-w-xs">
    <% if @category.errors.any? %>

      <div>
        <h1>The following errors prevented the <%= @category.class.name.downcase %> from being saved</h1>
        <ul class="ml-5 list-disc bg-gray-200 my-5">
          <% @category.errors.full_messages.each do |msg| %>
            <li class="text-red-500 text-xs"><%= msg %></li>
          <% end %>
        </ul>
      </div>

    <% end %>
    <%= form_with(model: @category ,class:'bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4', local: true) do |f|  %>
      <div class="mb-4">
        <%= f.label :name, 'Category name' ,class:'block text-gray-700 text-sm font-bold mb-2' %><br>
        <%= f.text_field :name , class:"shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder:"Enter name" %>
      </div>
      <div class="flex items-center justify-center">
        <%= f.submit class:"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      </div>
      </div>
    <% end %>


    </div>

app/views/categories/edit.html.erb
<h1 class="font-bold text-2xl text-center mt-10">Edit category name</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-black text-2xl font-bold text-center">Categories list page</h1>
<div class="flickr_pagination">
  <%= page_entries_info @categories %>
  <%= will_paginate @categories, :container => false %>
</div>
<table class="min-w-full leading-normal">
  <thead>
  <tr>
    <th
      class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-center text-xs font-semibold text-gray-600 uppercase tracking-wider">
      Title
    </th>
    <th colspan="3"
        class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-center text-xs font-semibold text-gray-600 uppercase tracking-wider">
      Action
    </th>
  </tr>
  </thead>
  <tbody>
  <% @categories.each do |category| %>
    <tr>
      <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
        <p class="text-gray-900 whitespace-no-wrap text-center"><%= category.name %></p>
      </td>
      <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
        <p class="underline  text-blue-500 whitespace-no-wrap text-center"><%= link_to 'Show', category_path(category)  %></p>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<div class="flickr_pagination">
  <%= page_entries_info @categories %>
  <%= will_paginate @categories, :container => false %>
</div>
<h2 class="underline text-blue-500 whitespace-no-wrap text-center">
  <%= link_to 'Crate new article' , new_category_path %>
</h2>

app/views/categories/new.html.erb
<h1 class="font-bold text-2xl text-center mt-10">Create new category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<div class="grid place-items-center w-full ">
  <div class="w-1/2 mx-20 py-4 px-8 bg-white  shadow-lg rounded-lg my-20">
  <div>
    <%= link_to @category.name, @category , class:'text-gray-800 text-2xl text-center font-semibold' %>
    <p class="text-2xl text-center"><%= pluralize(@category.articles.count, "article") %></p>
    <div class="flex  justify-center space-x-4 mt-5">
        <% if logged_in? && current_user.admin? %>
          <div>
            <%= link_to "Edit category", edit_category_path(@category), class: "px-4 py-2 rounded-md text-sm font-medium border-0 focus:outline-none focus:ring transition text-white bg-red-500 hover:bg-red-600 active:bg-red-700 focus:ring-red-300" %>
          </div>
        <% end %>
    </div>
  </div>
  <div class="flex justify-end mt-4">
    <p  class="text-sm font-medium text-indigo-500">Joined <%= time_ago_in_words(@category.created_at) %> ago</p>

  </div>
</div>
</div>
<%= render 'articles/articles' %>

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
  <% if name == 'alert' %>
    <div class="flex justify-center items-center m-1 font-medium py-1 px-2 bg-white rounded-md text-red-700 bg-red-100 border border-red-300 ">
    <div slot="avatar">
      <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-alert-octagon w-5 h-5 mx-2">
        <polygon points="7.86 2 16.14 2 22 7.86 22 16.14 16.14 22 7.86 22 2 16.14 2 7.86 7.86 2"></polygon>
        <line x1="12" y1="8" x2="12" y2="12"></line>
        <line x1="12" y1="16" x2="12.01" y2="16"></line>
      </svg>
    </div>
    <div class="text-xl font-normal  max-w-full flex-initial">
      <%= msg %></div>
    <div class="flex flex-auto flex-row-reverse">
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x cursor-pointer hover:text-red-400 rounded-full w-5 h-5 ml-2">
          <line x1="18" y1="6" x2="6" y2="18"></line>
          <line x1="6" y1="6" x2="18" y2="18"></line>
        </svg>
      </div>
    </div>
  </div>
  <% else %>
    <div class="flex justify-center items-center m-1 font-medium py-1 px-2 bg-white rounded-md text-green-700 bg-green-100 border border-green-300 ">
      <div slot="avatar">
        <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-check-circle w-5 h-5 mx-2">
          <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path>
          <polyline points="22 4 12 14.01 9 11.01"></polyline>
        </svg>
      </div>
      <div class="text-xl font-normal  max-w-full flex-initial">
        <%= msg %></div>
      <div class="flex flex-auto flex-row-reverse">
        <div>
          <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x cursor-pointer hover:text-green-400 rounded-full w-5 h-5 ml-2">
            <line x1="18" y1="6" x2="6" y2="18"></line>
            <line x1="6" y1="6" x2="18" y2="18"></line>
          </svg>
        </div>
      </div>
    </div>
    <%end  %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="container flex justify-around py-8 mx-auto bg-white">
  <div class="flex items-center">
    <h3 class="text-2xl font-medium text-blue-500">LOGO</h3>
  </div>
  <!-- left header section -->
  <div class="items-center hidden space-x-8 lg:flex">
    <%= link_to 'Bloggers', users_path , class: 'text-lg text-black' %>
    <% if logged_in? %>
      <div class="relative">
        <input type="checkbox" id="sortboxtwo" class="hidden absolute">
        <label for="sortboxtwo" class="flex items-center space-x-1 cursor-pointer">
          <span class="text-xg"><%="(Admin)" if current_user.admin?  %></span><span class="text-lg">Profile[<%= current_user.username %>]</span>
          <svg class="h-4 w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
          </svg>
        </label>

        <div id="sortboxmenutwo" class="absolute mt-1 right-1 top-full min-w-max shadow rounded opacity-0 bg-gray-300 border border-gray-400 transition delay-75 ease-in-out z-10">
          <ul class="block text-right text-gray-900">
            <li>
              <%= link_to 'View your profile' , user_path(current_user), class:'block px-3 py-2 hover:bg-gray-200' %>
            </li>
            <li>
              <%= link_to 'Edit your profile' , edit_user_path(current_user), class: 'block px-3 py-2 hover:bg-gray-200'%>
            </li>
            <li>
              <%= link_to 'Delete profile' , user_path(current_user), method: :delete, data: { confirm: "Are you sure?" }, class: 'block text-red-500 px-3 py-2 hover:bg-gray-200'%>
            </li>
          </ul>
        </div>
      </div>
    <% end %>
    <div class="relative">
      <input type="checkbox" id="sortbox" class="hidden absolute">
      <label for="sortbox" class="flex items-center space-x-1 cursor-pointer">
        <span class="text-lg">Articles</span>
        <svg class="h-4 w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
        </svg>
      </label>

      <div id="sortboxmenu" class="absolute mt-1 right-1 top-full min-w-max shadow rounded opacity-0 bg-gray-300 border border-gray-400 transition delay-75 ease-in-out z-10">
        <ul class="block text-right text-gray-900">
          <% if logged_in? %>
            <li>
              <%= link_to 'Create new article' , new_article_path, class:'block px-3 py-2 hover:bg-gray-200' %>
            </li>
          <% end %>
          <li>
            <%= link_to 'View articles' , articles_path, class: 'block px-3 py-2 hover:bg-gray-200'%>
          </li>
          <li><a href="#" class="block px-3 py-2 hover:bg-gray-200">Something else here</a></li>
        </ul>
      </div>
    </div>
    <div class="relative">
      <input type="checkbox" id="sortbox2" class="hidden absolute">
      <label for="sortbox2" class="flex items-center space-x-1 cursor-pointer">
        <span class="text-lg">Categories</span>
        <svg class="h-4 w-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
        </svg>
      </label>

      <div id="sortboxmenu2" class="absolute mt-1 right-1 top-full min-w-max shadow rounded opacity-0 bg-gray-300 border border-gray-400 transition delay-75 ease-in-out z-10">
        <ul class="block text-right text-gray-900">
          <% if logged_in? && current_user.admin? %>
            <li>
              <%= link_to 'Create new category' , new_category_path, class:'block px-3 py-2 hover:bg-gray-200' %>
            </li>
          <% end %>
          <li>
            <%= link_to 'View categories' , categories_path, class: 'block px-3 py-2 hover:bg-gray-200'%>
          </li>
          <li><a href="#" class="block px-3 py-2 hover:bg-gray-200">Something else here</a></li>
        </ul>
      </div>
    </div>

    <a href="">About Us</a>
  </div>
  <!-- right header section -->
  <div class="flex items-center space-x-2">
    <% if logged_in? %>
      <%= link_to current_user.username, user_path(current_user), class:"px-4 py-2 text-blue-100 bg-blue-800 rounded-md"  %>

      <%= link_to 'logout', logout_path, method: :delete, class:"px-4 py-2 text-blue-100 bg-blue-800 rounded-md"  %>
    <%else %>
      <%= link_to 'login in', login_path, class:"px-4 py-2 text-blue-100 bg-blue-800 rounded-md"  %>
      <%= link_to 'signup', signup_path, class:"px-4 py-2 text-gray-200 bg-gray-400 rounded-md"  %>
  <%end %>
  </div>
</nav>

app/views/users/edit.html.erb
<h1 class="font-bold text-2xl text-center mt-10">Edit your profile</h1>

<div class="flex justify-center mt-10">
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<h1 class="mt-10 text-center text-2xl text-blue-700 font-bold"> Alpha bloggers</h1>

<div class="flickr_pagination">
    <%= page_entries_info @users %>
  <%= will_paginate @users, :container => false %>
</div>
<div class="grid place-items-center w-full ">
  <% @users.each do |user| %>
    <div class="w-1/2 mx-20 py-4 px-8 bg-white  shadow-lg rounded-lg my-20">
      <div class="flex justify-center md:justify-end -mt-16">
        <%= link_to gravatar_for(user, size: 70), user  %>
      </div>
      <div>
        <%= link_to user.username, user , class:'text-gray-800 text-2xl text-center font-semibold' %>
        <p class="text-2xl text-center"><%= pluralize(user.articles.count, "article") %></p>
        <div class="flex  justify-center space-x-4 mt-5">
          <div>
            <%= link_to "View profile", user, class: "px-4 py-2 rounded-md text-sm font-medium border-0 focus:outline-none focus:ring transition text-white bg-yellow-500 hover:bg-yellow-600 active:bg-yellow-700 focus:ring-yellow-300" %>
          </div>
          <% if logged_in? %>
            <% if user == current_user %>
              <div>
                <%= link_to "Edit profile", edit_user_path(user), class: "px-4 py-2 rounded-md text-sm font-medium border-0 focus:outline-none focus:ring transition text-white bg-red-500 hover:bg-red-600 active:bg-red-700 focus:ring-red-300" %>
              </div>
            <% end %>
            <% if  current_user.admin? %>
              <div>
                <%= link_to "Delete user",user_path(user),method: :delete,data: {confirm: 'are you sure you want to delete the user and all associated articles?'}, class: "px-4 py-2 rounded-md text-sm font-medium border-0 focus:outline-none focus:ring transition text-white bg-red-500 hover:bg-red-600 active:bg-red-700 focus:ring-red-300" %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="flex justify-end mt-4">
        <p  class="text-sm font-medium text-indigo-500">Joined <%= time_ago_in_words(user.created_at) %> ago</p>

      </div>
    </div>
  <% end %>
  <div class="flickr_pagination mb-5">
    <%= page_entries_info @users %>
    <%= will_paginate @users, :container => false %>
  </div>

</div>

app/views/users/new.html.erb
<h1 class="font-bold text-2xl text-center mt-10">Sign up for Alpha Blog</h1>

<div class="flex justify-center mt-10">
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<h1 class="font-bold text-2xl text-center mt-10"><%= @user.username %> Profile </h1>
<div class="flex justify-center">
  <%= gravatar_for @user, size: 200   %>

  <p class="font-bold text-2xl text-center mt-10">Articles</p>
</div>
<%= render 'articles/articles'  %>